
server:
  port: 8080

spring:
  data:
    mongodb:
      database: ${SPRING_DATA_MONGODB_MS_PRODUCTS_DATABASE:ms_products}
      port: ${SPRING_DATA_MS_PRODUCTS_PORT:27017}
      host: ${SPRING_DATA_MS_PRODUCTS_HOST:mongodb-ms-products}
